### ISSUE TITLE
Tool Throws an Unknown Error Message: "An Error Occurred"

### ISSUE THREAD

**Issue by naroner** [Equipment-and-Tool-Institute/j1939-84#1187]
**During part 2 "An Error Occurred" popup is displayed:**
![84 tool error](https://user-images.githubusercontent.com/101883690/188652229-fdbe0d41-3d6e-4a7c-a90d-044b8fef794e.PNG)

**From j1939_840.log:**
2022-08-10 15:44:14.404 SEVERE org.etools.j1939_84.controllers.Controller lambda$getRunnable$0 Error
**java.lang.NullPointerException**
	at org.etools.j1939_84.controllers.part02.Part02Step17Controller.lambda$testSp12730$21(Part02Step17Controller.java:624)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at org.etools.j1939_84.controllers.part02.Part02Step17Controller.testSp12730(Part02Step17Controller.java:615)
	at org.etools.j1939_84.controllers.part02.Part02Step17Controller.run(Part02Step17Controller.java:343)
	at org.etools.j1939_84.controllers.Controller.lambda$getRunnable$0(Controller.java:290)
	at org.etools.j1939_84.controllers.Controller.run(Controller.java:372)
	at org.etools.j1939_84.controllers.PartController.run(PartController.java:74)
	at org.etools.j1939_84.controllers.Controller.lambda$getRunnable$0(Controller.java:290)
	at org.etools.j1939_84.controllers.Controller.run(Controller.java:372)
	at org.etools.j1939_84.controllers.OverallController.run(OverallController.java:97)
	at org.etools.j1939_84.controllers.Controller.lambda$getRunnable$0(Controller.java:290)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by ericthomasswenson** [comment]
Also observed by Anthony Best

**Comment by battjt** [comment]
Was addressed as part of 6.2.17 rewrite.

**Comment by naroner** [comment]
@ericthomasswenson I haven't seen this in a while and didn't notice it in 3.1.19
