### ISSUE TITLE
GHG Active Technology Tabular Display Not Observed in Part 11

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1224]
GHG Active Technology Tabular Display Not Observed in Parts 1, 2, and 11. V. 3.1.13

14:09:13.9421 Destination Specific GHGTTS Request to Engine #1 (0)
14:09:13.9450 18EA00F9 [3] FF FA 00 (TX)
14:09:14.2614 1CFAFF00 [40] 05 00 00 00 00 06 00 00 00 00 07 00 00 00 00 F6 00 00 00 00 F7 00 00 00 00 F8 00 00 00 00 F9 00 00 00 00 FA 00 00 00 00
Green House Gas Stored 100 Hour Active Technology Tracking from Engine #1 (0): 
  Active Technology:  Vehicle Speed Limiting Technology (5), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Predictive Cruise Control (6), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Auto Neutral (7), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Mfg Defined Active Technology 5 (246), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Mfg Defined Active Technology 4 (247), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Mfg Defined Active Technology 1 (250), Time = 0,000 s, Vehicle Distance = 0,000 km

**** missing here **** for 11.13.19.b

End Test 11.13 - NOx Binning and GHG tracking for MY2022+ Engines and Vehicles

**Comment by battjt** [comment]
stack trace for similar failure in 1.26
```
2023-02-07 09:22:05.814 SEVERE org.etools.j1939tools.j1939.packets.GhgActiveTechnologyPacket toString Error creating string
java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -3 is negative
	at java.base/java.lang.System.arraycopy(Native Method)
	at java.base/java.util.Arrays.copyOfRange(Unknown Source)
	at org.etools.j1939tools.j1939.model.ActiveTechnology.lambda$create$0(ActiveTechnology.java:26)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.etools.j1939tools.j1939.model.ActiveTechnology.create(ActiveTechnology.java:32)
	at org.etools.j1939tools.j1939.packets.GhgActiveTechnologyPacket.getActiveTechnologies(GhgActiveTechnologyPacket.java:34)
	at org.etools.j1939tools.j1939.packets.GhgActiveTechnologyPacket.toString(GhgActiveTechnologyPacket.java:46)
	at org.etools.j1939tools.j1939.J1939.lambda$requestDSOnce$12(J1939.java:633)
	at java.base/java.util.Optional.ifPresentOrElse(Unknown Source)
	at org.etools.j1939tools.j1939.J1939.requestDSOnce(J1939.java:630)
	at org.etools.j1939tools.j1939.J1939.requestDS(J1939.java:586)
	at org.etools.j1939tools.modules.CommunicationsModule.request(CommunicationsModule.java:522)
	at org.etools.j1939_84.controllers.StepController.requestPackets(StepController.java:160)
	at org.etools.j1939_84.controllers.part01.Part01Step26Controller.testSp12730(Part01Step26Controller.java:560)
	at org.etools.j1939_84.controllers.part01.Part01Step26Controller.run(Part01Step26Controller.java:342)
```

**Comment by ericthomasswenson** [comment]
Yes, it was also missing in part 1

13:29:24.4979 Destination Specific GHGTTS Request to Engine #1 (0)
13:29:24.4994 18EA00F9 [3] FF FA 00 (TX)
13:29:24.8165 1CFAFF00 [40] [05 00 00 00 00 06 00](tel:05 00 00 00 00 06 00) [00 00 00 07 00 00 00](tel:00 00 00 07 00 00 00) 00 F6 [00 00 00 00](tel:00 00 00 00) F7 [00 00 00 00](tel:00 00 00 00) F8 [00 00 00 00](tel:00 00 00 00) F9 [00 00 00 00](tel:00 00 00 00) FA [00 00 00 00](tel:00 00 00 00)
Green House Gas Stored 100 Hour Active Technology Tracking from Engine #1 (0): 
  Active Technology:  Vehicle Speed Limiting Technology (5), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Predictive Cruise Control (6), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Auto Neutral (7), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Mfg Defined Active Technology 5 (246), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Mfg Defined Active Technology 4 (247), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Mfg Defined Active Technology 1 (250), Time = 0,000 s, Vehicle Distance = 0,000 km


**** missing here **** for part 1

End Test 1.26 - Data stream support verification

**Comment by ericthomasswenson** [comment]
And part 2.

13:31:38.8470 Destination Specific GHGTTS Request to Engine #1 (0)
13:31:38.8512 18EA00F9 [3] FF FA 00 (TX)
13:31:39.1763 1CFAFF00 [40] [05 00 00 00 00 06 00](tel:05 00 00 00 00 06 00) [00 00 00 07 00 00 00](tel:00 00 00 07 00 00 00) 00 F6 [00 00 00 00](tel:00 00 00 00) F7 [00 00 00 00](tel:00 00 00 00) F8 [00 00 00 00](tel:00 00 00 00) F9 [00 00 00 00](tel:00 00 00 00) FA [00 00 00 00](tel:00 00 00 00)
Green House Gas Stored 100 Hour Active Technology Tracking from Engine #1 (0): 
  Active Technology:  Vehicle Speed Limiting Technology (5), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Predictive Cruise Control (6), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Auto Neutral (7), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Mfg Defined Active Technology 5 (246), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Mfg Defined Active Technology 4 (247), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0,000 s, Vehicle Distance = 0,000 km
  Active Technology:  Mfg Defined Active Technology 1 (250), Time = 0,000 s, Vehicle Distance = 0,000 km


**** missing here **** for part 2 

End Test 2.17 - KOER Datastream verification
