### ISSUE TITLE
Error: arraycopy: length -1 is negative, observed during PSI SI Part 1 testing

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#959]
Error: arraycopy: length -1 is negative, observed during PSI SI Part 1 testing of V3.0.7.

Presumed fix is to protect the arraycopy by checking the length first.

![image](https://user-images.githubusercontent.com/78398059/115918639-c208fe00-a445-11eb-882c-8e22e9c9431e.jpeg)

**Comment by ericthomasswenson** [comment]
[v307 error message.docx](https://github.com/battjt/j1939-84/files/6367664/v307.error.message.docx) — error message screen capture 
[v307 gasoline SI Link2.docx](https://github.com/battjt/j1939-84/files/6367669/v307.gasoline.SI.Link2.docx) — Report file from run with error.
[v307 old ISB Link2 c.docx](https://github.com/battjt/j1939-84/files/6367671/v307.old.ISB.Link2.c.docx) — report file for comparison

**Comment by gumbelmj** [comment]
```
2021-04-23 12:13:50.234 SEVERE org.etools.j1939_84.controllers.Controller lambda$getRunnable$0 Error
java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -1 is negative
	at java.base/java.lang.System.arraycopy(Native Method)
	at java.base/java.util.Arrays.copyOfRange(Unknown Source)
	at org.etools.j1939_84.bus.j1939.packets.model.SpnDataParser.parse(SpnDataParser.java:29)
	at org.etools.j1939_84.bus.j1939.packets.GenericPacket.getSpns(GenericPacket.java:104)
	at org.etools.j1939_84.controllers.TableA1Validator.reportNotAvailableSPNs(TableA1Validator.java:386)
	at org.etools.j1939_84.controllers.part02.Part02Step17Controller.lambda$run$2(Part02Step17Controller.java:123)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at org.etools.j1939_84.bus.MultiQueue$SpliteratorImplementation.tryAdvance(MultiQueue.java:161)
	at java.base/java.util.Spliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.etools.j1939_84.controllers.part02.Part02Step17Controller.run(Part02Step17Controller.java:149)
	at org.etools.j1939_84.controllers.Controller.lambda$getRunnable$0(Controller.java:269)
	at org.etools.j1939_84.controllers.Controller.run(Controller.java:351)
	at org.etools.j1939_84.controllers.PartController.run(PartController.java:74)
	at org.etools.j1939_84.controllers.Controller.lambda$getRunnable$0(Controller.java:269)
	at org.etools.j1939_84.controllers.Controller.run(Controller.java:351)
	at org.etools.j1939_84.controllers.OverallController.run(OverallController.java:97)
	at org.etools.j1939_84.controllers.Controller.lambda$getRunnable$0(Controller.java:269)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by gumbelmj** [comment]
The offending packet is:
```
18FEE300 [34] 00 19 B3 C8 36 D0 E8 1C B8 60 22 C8 C8 36 D0 C8 36 FF FF 55 04 38 5E 14 46 AF 7D C8 C8 36 86 00 D2 03
```

According to J1939DA, this message should be 40 bytes long.

**Comment by battjt** [comment]
I'm unclear on what he expected outcome should be.  @ericthomasswenson  should we just ignore the malformed packet?  Parse what we can?  Clearly the current error message is not clear enough.

**Comment by ericthomasswenson** [comment]
Please assume the truncated bytes are not supported in 
_**18FEE300 [34] 00 19 B3 C8 36 D0** E8 1C B8 60 22 C8 C8 **36 D0 C8 36 FF FF 55** 04 38 5E 14 46 AF 7D **C8 C8 36 86 00 D2 03**_   
My recollection is that unsupported data may be truncated ... this is a backwards compatibility hedge as multiple frame messages are extended with new data at the end. Transmitting an (empty) TP.DT frame containing all FFh as the payload would be inappropriate. 

The data received may be padded with FF FF FF FF FF FFh, If that makes processing the resulting message easier.  (Pad the number of missing bytes, to meet your assumption of a 40 byte length ... Or initialize the data structure with FFh and only copy the length of data provided). If a supported SP was sent as FF in this manner, provide the Table A-1 message indicated (or Fail, if supported in DM24, sent as FFh, and not listed in Table A-1). 

There are fields apparently in FEE3 (EC1) that are useful for the subject SI engine. (Or the data was sent assuming an older record layout).

It’s not hard to imagine a naturally aspirated SI engine with a traditional throttle plate would have no use for

**_SPN 7828, Engine Default Idle Torque Limit_**  

Throttle plates, I believe, control the available power through the restriction of air flow.

In the Diesel example below the data omitted by the SI engine is highlighted.
PGN 65251 with Supported SPNs 539, 540, 541, 542, 543, 544
13:08:42.8724 18FEE300 [40] C0 12 A9 80 25 CF 00 19 B8 20 1C C8 80 25 CF 80 25 FF FF 0D 0C 20 4E 3C 3C 78 7D C8 80 25 A5 01 0A 04 **_FF FF FF FF FF A0_**
Found: Engine Configuration 1 from Engine #1 (0): 
  SPN   188, Engine Speed At Idle, Point 1: 600.000000 rpm
  SPN   539, Engine Percent Torque At Idle, Point 1: 44.000000 %
  SPN   528, Engine Speed At Point 2: 1200.000000 rpm
  SPN   540, Engine Percent Torque At Point 2: 82.000000 %
  SPN   529, Engine Speed At Point 3: 800.000000 rpm
  SPN   541, Engine Percent Torque At Point 3: 59.000000 %
  SPN   530, Engine Speed At Point 4: 900.000000 rpm
  SPN   542, Engine Percent Torque At Point 4: 75.000000 %
  SPN   531, Engine Speed At Point 5: 1200.000000 rpm
  SPN   543, Engine Percent Torque At Point 5: 82.000000 %
  SPN   532, Engine Speed At High Idle, Point 6: 1200.000000 rpm
  SPN   545, Engine Gain (Kp) Of The Endspeed Governor: Not Available
  SPN   544, Engine Reference Torque: 3085.000000 Nm
  SPN   533, Engine Maximum Momentary Override Speed, Point 7: 2500.000000 rpm
  SPN   534, Engine Maximum Momentary Override Time Limit: 6.000000 s
  SPN   535, Engine Requested Speed Control Range Lower Limit: 600.000000 rpm
  SPN   536, Engine Requested Speed Control Range Upper Limit: 1200.000000 rpm
  SPN   537, Engine Requested Torque Control Range Lower Limit: 0.000000 %
  SPN   538, Engine Requested Torque Control Range Upper Limit: 75.000000 %
  SPN  1712, Engine Requested Speed Control Range Upper Limit (Extended Range): 1200.000000 rpm
  SPN  1794, Engine Moment of Inertia: 1.684000 kg•m²
  SPN  1846, Engine Default Torque Limit: 1034.000000 Nm
  **_SPN  3344, Support Variable Rate TSC1 Message: 11111111
  SPN  3345, Support TSC1 Control Purpose Group 1: 11111111
  SPN  3346, Support TSC1 Control Purpose Group 2: 11111111
  SPN  3347, Support TSC1 Control Purpose Group 3: 11111111
  SPN  3348, Support TSC1 Control Purpose Group 4: 11111111
  SPN  7828, Engine Default Idle Torque Limit: 35.000000 %_**

**Comment by ericthomasswenson** [comment]
There are some multi frame after treatment PGs, that may be sent as truncated entities too.

We can analyze those as an enhancement, perhaps.

**Comment by ericthomasswenson** [comment]
I recommend padding the perceived missing bytes at the end of the EC1 message with FFh ... this cannot be assumed to be a fixed length message when the ending SPs are not supported. See #959 comment for more explanation.
